const coreOta = {
    "total_count": 263,
    "sentences": [
        {
            "sentence_id": 8234839417,
            "created_date": 1695176451264,
            "natural_id": "650a47ec22f0d01187d72631",
            "attributes": {
                "_language": "english",
                "review_id": "650a47ec22f0d01187d72631",
                "cb_document_word_count": 6,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385232201,
                "hr_servicescore": 1,
                "hr_travelertype": "partner",
                "ha_tuid": "72615891",
                "_languagedetected": "english",
                "_sentence_end_pos": 31,
                "_id_batch": 61522260,
                "_id_document": 5403265447,
                "ha_hotelname": "hotel 1",
                "hr_tpid": 1,
                "hr_product_brand": "ex",
                "hr_ecofriendlyscore": "2.0",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "06:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 3,
                "natural_id": "650a47ec22f0d01187d72631",
                "cb_date_updated": 1695176451527,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "218422924",
                "_degreesentimentindex": -2,
                "_sentence_start_pos": 0,
                "cb_date_created_utc": 1695176451264,
                "hr_roomcleanlinesssc": 2,
                "cb_sentence_word_count": 6,
                "cb_content_type": "contentful",
                "hr_itin": "9143780707730",
                "_id_sentence": 8234839417,
                "_doc_time": "2023-09-20T01:16:28.000Z",
                "hr_displaylocale": "en_us",
                "hr_hotelconditionsco": 1,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "hr_triptype": "leisure",
                "adm_expediahotelid": "1040714",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "dynamic_collection",
                "cb_sentence_quartile": 1,
                "_words": "There are roaches on the floor.",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "Health and Safety - Ref": [
                    "Health and Safety - Ref >> Pest-Control"
                ]
            },
            "classification_timestamps": {
                "Health and Safety - Ref": 1695178955426
            }
        },
        {
            "sentence_id": 8234825799,
            "created_date": 1695168191331,
            "natural_id": "650a2871db4f6e19c7a17487",
            "attributes": {
                "_language": "english",
                "review_id": "650a2871db4f6e19c7a17487",
                "cb_document_word_count": 8,
                "hr_submissiontime": "2023-09-19",
                "_id_source": "not specified",
                "_id_verbatim": 15385224986,
                "hr_servicescore": 1,
                "hr_travelertype": "friends",
                "ha_tuid": "1273503759",
                "_languagedetected": "english",
                "_sentence_end_pos": 32,
                "_id_batch": 61520043,
                "_id_document": 5400752446,
                "ha_hotelname": "hotel 2",
                "hr_tpid": 1,
                "hr_product_brand": "ex",
                "hr_ecofriendlyscore": "1.0",
                "_doc_date": "2023-09-19",
                "cb_interaction_type": "feedback",
                "time_of_day": "04:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 1,
                "natural_id": "650a2871db4f6e19c7a17487",
                "cb_date_updated": 1695168191738,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "314051729",
                "_degreesentimentindex": -3,
                "_sentence_start_pos": 0,
                "cb_date_created_utc": 1695168191331,
                "hr_roomcleanlinesssc": 1,
                "cb_sentence_word_count": 4,
                "cb_content_type": "contentful",
                "hr_itin": "9138971191036",
                "_id_sentence": 8234825799,
                "_doc_time": "2023-09-19T23:02:09.000Z",
                "hr_displaylocale": "en_us",
                "hr_hotelconditionsco": 1,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "hr_triptype": "business",
                "adm_expediahotelid": "5273",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "dynamic_collection",
                "cb_sentence_quartile": 1,
                "_words": "so many cockroaches - unlivable.",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "Health and Safety - Ref": [
                    "Health and Safety - Ref >> Pest-Control"
                ]
            },
            "classification_timestamps": {
                "Health and Safety - Ref": 1695170148709
            }
        },
        {
            "sentence_id": 8234819483,
            "created_date": 1695164516331,
            "natural_id": "650a17ca2e6cb12c43b973e5",
            "attributes": {
                "_language": "dutch",
                "review_id": "650a17ca2e6cb12c43b973e5",
                "cb_document_word_count": 62,
                "hr_submissiontime": "2023-09-19",
                "_id_source": "not specified",
                "_id_verbatim": 15385222046,
                "hr_servicescore": 2,
                "hr_travelertype": "partner",
                "ha_tuid": "11764307",
                "_languagedetected": "dutch",
                "_sentence_end_pos": 82,
                "cb_emotion": [
                    "joy"
                ],
                "_id_batch": 61520043,
                "_id_document": 5399749452,
                "ha_hotelname": "hotel 3",
                "hr_tpid": 11,
                "cb_emotion_intensity": 2,
                "hr_product_brand": "ex",
                "hr_ecofriendlyscore": "3.0",
                "_doc_date": "2023-09-19",
                "cb_interaction_type": "feedback",
                "time_of_day": "02:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 3,
                "natural_id": "650a17ca2e6cb12c43b973e5",
                "cb_date_updated": 1695164517689,
                "hr_lastmodificationt": "2023-09-19",
                "hr_roomtypeid": "201206556",
                "_degreesentimentindex": 0.25,
                "_sentence_start_pos": 0,
                "cb_date_created_utc": 1695164516331,
                "hr_roomcleanlinesssc": 3,
                "cb_sentence_word_count": 13,
                "cb_content_type": "contentful",
                "hr_itin": "9141181263241",
                "_id_sentence": 8234819483,
                "_doc_time": "2023-09-19T21:51:06.000Z",
                "hr_displaylocale": "nl_nl",
                "hr_hotelconditionsco": 3,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "hr_triptype": "leisure",
                "adm_expediahotelid": "11849074",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "dynamic_collection",
                "cb_sentence_quartile": 1,
                "_words": "Mooi hotel, schoon (op kit randen douche, een dode kakkerlak en rioolwormpjes na).",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "Health and Safety - Ref": [
                    "Health and Safety - Ref >> Pest-Control"
                ]
            },
            "classification_timestamps": {
                "Health and Safety - Ref": 1695170148709
            }
        },
        {
            "sentence_id": 8234924110,
            "created_date": 1695230258477,
            "natural_id": "650b19fb2c341f1193e563f1",
            "attributes": {
                "_language": "portuguese",
                "review_id": "650b19fb2c341f1193e563f1",
                "cb_document_word_count": 64,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385274993,
                "hr_servicescore": 3,
                "ha_tuid": "118598151",
                "_languagedetected": "portuguese",
                "_sentence_end_pos": 122,
                "_id_batch": 61535523,
                "_id_document": 5417268446,
                "ha_hotelname": "hotel 4",
                "hr_tpid": -1,
                "hr_product_brand": "hotels",
                "hr_ecofriendlyscore": "2.0",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "21:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 1,
                "natural_id": "650b19fb2c341f1193e563f1",
                "cb_date_updated": 1695230259351,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "200061934",
                "_degreesentimentindex": -1.5,
                "_sentence_start_pos": 20,
                "cb_date_created_utc": 1695230258477,
                "hr_roomcleanlinesssc": 1,
                "cb_sentence_word_count": 19,
                "cb_content_type": "contentful",
                "hr_itin": "9213547103220",
                "_id_sentence": 8234924110,
                "_doc_time": "2023-09-20T16:12:43.000Z",
                "hr_displaylocale": "pt_br",
                "hr_hotelconditionsco": 2,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "adm_expediahotelid": "4316320",
                "hr_roomcomfortscore": 2,
                "adm_datasourceid": "dynamic_collection",
                "cb_sentence_quartile": 1,
                "_words": "ficamos em um quarto ao lado da lixeira, onde encontramos baratas próximas e quarto com cheiro de mofo",
                "review_title": "péssima experiência",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "Health and Safety - Ref": [
                    "Health and Safety - Ref >> Pest-Control"
                ]
            },
            "classification_timestamps": {
                "Health and Safety - Ref": 1695235628062
            }
        },
        {
            "sentence_id": 8234938329,
            "created_date": 1695235985180,
            "natural_id": "650b306a0d0e354add0b045a",
            "attributes": {
                "_language": "english",
                "review_id": "650b306a0d0e354add0b045a",
                "cb_document_word_count": 90,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385281611,
                "hr_servicescore": 1,
                "hr_travelertype": "partner",
                "ha_tuid": "1622963622",
                "_languagedetected": "english",
                "_sentence_end_pos": 219,
                "_id_batch": 61536546,
                "_id_document": 5419657460,
                "ha_hotelname": "hotel 5",
                "hr_tpid": 1,
                "hr_product_brand": "expedia",
                "hr_ecofriendlyscore": "1.0",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "22:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 1,
                "natural_id": "650b306a0d0e354add0b045a",
                "cb_date_updated": 1695235985612,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "205736",
                "_degreesentimentindex": -2,
                "_sentence_start_pos": 101,
                "cb_date_created_utc": 1695235985180,
                "hr_roomcleanlinesssc": 1,
                "cb_sentence_word_count": 27,
                "cb_content_type": "contentful",
                "hr_itin": "9138854510954",
                "_id_sentence": 8234938329,
                "_doc_time": "2023-09-20T17:48:26.000Z",
                "hr_displaylocale": "en_us",
                "hr_hotelconditionsco": 0,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "hr_triptype": "both business/leisure",
                "adm_expediahotelid": "118511",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "dynamic_collection",
                "cb_sentence_quartile": 1,
                "_words": "I had roaches in my room and they did not seem TJ care about the fact that they were all over the walls and on the bed.",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "Health and Safety - Ref": [
                    "Health and Safety - Ref >> Pest-Control"
                ]
            },
            "classification_timestamps": {
                "Health and Safety - Ref": 1695240243972
            }
        },
        {
            "sentence_id": 8234874203,
            "created_date": 1695207529484,
            "natural_id": "650ac1af5e2b0e17a5a1f1e3",
            "attributes": {
                "_language": "english",
                "review_id": "650ac1af5e2b0e17a5a1f1e3",
                "cb_document_word_count": 23,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385251812,
                "hr_servicescore": 2,
                "hr_travelertype": "family",
                "ha_tuid": "702439529",
                "_languagedetected": "english",
                "_sentence_end_pos": 71,
                "_id_batch": 61530105,
                "_id_document": 5409048447,
                "ha_hotelname": "hotel  6",
                "hr_tpid": 1,
                "cb_emotion_intensity": 2,
                "hr_product_brand": "ex",
                "hr_ecofriendlyscore": "1.0",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "14:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 1,
                "natural_id": "650ac1af5e2b0e17a5a1f1e3",
                "cb_date_updated": 1695207529849,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "218130500",
                "_degreesentimentindex": -2.5,
                "_sentence_start_pos": 16,
                "cb_date_created_utc": 1695207529484,
                "hr_roomcleanlinesssc": 1,
                "cb_sentence_word_count": 11,
                "cb_content_type": "contentful",
                "hr_itin": "9144212099086",
                "_id_sentence": 8234874203,
                "_doc_time": "2023-09-20T09:55:59.000Z",
                "hr_displaylocale": "en_us",
                "hr_hotelconditionsco": 1,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "hr_triptype": "leisure",
                "adm_expediahotelid": "996191",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "dynamic_collection",
                "cb_sentence_quartile": 1,
                "_words": "Found roaches in the room and it was generally a dump..",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "Health and Safety - Ref": [
                    "Health and Safety - Ref >> Pest-Control"
                ]
            },
            "classification_timestamps": {
                "Health and Safety - Ref": 1695212114268
            }
        },
        {
            "sentence_id": 8234862465,
            "created_date": 1695195971580,
            "natural_id": "650a929f01262c6c3a000814",
            "attributes": {
                "_language": "english",
                "review_id": "650a929f01262c6c3a000814",
                "cb_document_word_count": 42,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385245068,
                "hr_servicescore": 3,
                "hr_travelertype": "partner",
                "ha_tuid": "604207317",
                "_languagedetected": "english",
                "_sentence_end_pos": 142,
                "_id_batch": 61526607,
                "_id_document": 5406982447,
                "ha_hotelname": "hotel 7",
                "hr_tpid": 4,
                "hr_product_brand": "ex",
                "hr_ecofriendlyscore": "3.0",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "11:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 2,
                "natural_id": "650a929f01262c6c3a000814",
                "cb_date_updated": 1695195971930,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "115127",
                "_degreesentimentindex": -2.5,
                "_sentence_start_pos": 54,
                "cb_date_created_utc": 1695195971580,
                "hr_roomcleanlinesssc": 2,
                "cb_sentence_word_count": 17,
                "cb_content_type": "contentful",
                "hr_itin": "9143957959400",
                "_id_sentence": 8234862465,
                "_doc_time": "2023-09-20T06:35:11.000Z",
                "hr_displaylocale": "en_ca",
                "hr_hotelconditionsco": 2,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "hr_triptype": "both business/leisure",
                "adm_expediahotelid": "17724",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "dynamic_collection",
                "cb_sentence_quartile": 1,
                "_words": "We also did not feel safe, especially after one of the guests got mugged in the elevator.",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "Health and Safety - Ref": [
                    "Health and Safety - Ref >> Lifts"
                ]
            },
            "classification_timestamps": {
                "Health and Safety - Ref": 1695198217698
            }
        },
        {
            "sentence_id": 8234955215,
            "created_date": 1695243947477,
            "natural_id": "650b4ff40d0e354add0b61b5",
            "attributes": {
                "_language": "english",
                "review_id": "650b4ff40d0e354add0b61b5",
                "cb_document_word_count": 21,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385289329,
                "hr_servicescore": 0,
                "ha_tuid": "1110836166",
                "_languagedetected": "english",
                "_sentence_end_pos": 119,
                "_id_batch": 61539326,
                "_id_document": 5421901446,
                "ha_hotelname": "hotel 8",
                "hr_tpid": 4,
                "hr_product_brand": "expedia",
                "hr_ecofriendlyscore": "2.0",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "01:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 2,
                "natural_id": "650b4ff40d0e354add0b61b5",
                "cb_date_updated": 1695243947751,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "95434",
                "_degreesentimentindex": -2.25,
                "_sentence_start_pos": 0,
                "cb_date_created_utc": 1695243947477,
                "hr_roomcleanlinesssc": 2,
                "cb_sentence_word_count": 21,
                "cb_content_type": "contentful",
                "hr_itin": "9136211010354",
                "_id_sentence": 8234955215,
                "_doc_time": "2023-09-20T20:03:00.000Z",
                "hr_displaylocale": "en_ca",
                "hr_hotelconditionsco": 2,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "hr_triptype": "leisure",
                "adm_expediahotelid": "1154628",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "dynamic_collection",
                "cb_sentence_quartile": 1,
                "_words": "Pool was never cleaned Shuffleboard full of sand and water No lighting in hallway at night unsafe No lighting at pool",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "Health and Safety - Ref": [
                    "Health and Safety - Ref >> Pool Safety"
                ]
            },
            "classification_timestamps": {
                "Health and Safety - Ref": 1695249428639
            }
        },
        {
            "sentence_id": 8234824453,
            "created_date": 1695167322235,
            "natural_id": "650a1a922e6cb12c43b97c51",
            "attributes": {
                "_language": "english",
                "review_id": "650a1a922e6cb12c43b97c51",
                "cb_document_word_count": 279,
                "hr_submissiontime": "2023-09-19",
                "_id_source": "not specified",
                "_id_verbatim": 15385224336,
                "hr_servicescore": 1,
                "hr_travelertype": "partner",
                "ha_tuid": "314785277",
                "_languagedetected": "english",
                "_sentence_end_pos": 448,
                "_id_batch": 61520043,
                "_id_document": 5400529447,
                "ha_hotelname": "hotel 9",
                "hr_tpid": 1,
                "hr_product_brand": "ex",
                "hr_ecofriendlyscore": "2.0",
                "_doc_date": "2023-09-19",
                "cb_interaction_type": "feedback",
                "time_of_day": "03:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 1,
                "natural_id": "650a1a922e6cb12c43b97c51",
                "cb_date_updated": 1695167323528,
                "hr_lastmodificationt": "2023-09-19",
                "hr_roomtypeid": "200904418",
                "_degreesentimentindex": -2,
                "_sentence_start_pos": 327,
                "cb_date_created_utc": 1695167322235,
                "hr_roomcleanlinesssc": 1,
                "cb_sentence_word_count": 22,
                "cb_content_type": "contentful",
                "hr_itin": "9143872998031",
                "_id_sentence": 8234824453,
                "_doc_time": "2023-09-19T22:02:58.000Z",
                "hr_displaylocale": "en_us",
                "hr_hotelconditionsco": 1,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "hr_triptype": "leisure",
                "adm_expediahotelid": "10057288",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "dynamic_collection",
                "cb_sentence_quartile": 1,
                "_words": "The next morning, we had noticed there were some bugs in the room, maybe not roaches but they were larger and concerning.",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "Health and Safety - Ref": [
                    "Health and Safety - Ref >> Pest-Control"
                ]
            },
            "classification_timestamps": {
                "Health and Safety - Ref": 1695170148710
            }
        },
        {
            "sentence_id": 8234829738,
            "created_date": 1695170385598,
            "natural_id": "650a2d58db4f6e19c7a187a8",
            "attributes": {
                "_language": "english",
                "review_id": "650a2d58db4f6e19c7a187a8",
                "cb_document_word_count": 180,
                "hr_submissiontime": "2023-09-19",
                "_id_source": "not specified",
                "_id_verbatim": 15385226982,
                "hr_servicescore": 1,
                "ha_tuid": "133123277",
                "_languagedetected": "english",
                "_sentence_end_pos": 755,
                "_id_batch": 61521308,
                "_id_document": 5401392446,
                "ha_hotelname": "hotel 10",
                "hr_tpid": -1,
                "hr_product_brand": "hotels",
                "hr_ecofriendlyscore": "1.0",
                "_doc_date": "2023-09-19",
                "cb_interaction_type": "feedback",
                "time_of_day": "04:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 1,
                "natural_id": "650a2d58db4f6e19c7a187a8",
                "cb_date_updated": 1695170386507,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "96355",
                "_degreesentimentindex": -2,
                "_sentence_start_pos": 700,
                "cb_date_created_utc": 1695170385598,
                "hr_roomcleanlinesssc": 1,
                "cb_sentence_word_count": 7,
                "cb_content_type": "contentful",
                "hr_itin": "9002384571501",
                "_id_sentence": 8234829738,
                "_doc_time": "2023-09-19T23:23:04.000Z",
                "hr_displaylocale": "en_us",
                "hr_hotelconditionsco": 1,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "adm_expediahotelid": "67407",
                "hr_roomcomfortscore": 3,
                "adm_datasourceid": "dynamic_collection",
                "cb_sentence_quartile": 3,
                "_words": "showed the lady at the desk the pictures of the roaches",
                "review_title": "nasty",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "Health and Safety - Ref": [
                    "Health and Safety - Ref >> Pest-Control"
                ]
            },
            "classification_timestamps": {
                "Health and Safety - Ref": 1695174373768
            }
        }
    ],
    "scroll_id": "1-757260788762607617-1-ITERATE-FGluY2x1ZGVfY29udGV4dF91dWlkDnF1ZXJ5VGhlbkZldGNoPBY0dDF4OUgweVRIYTlqM21NUGtyNzFRAAAAAA2US1cWZkZZNktLLVBRNnE2XzZTYnczU1dVdxZSX3NjdTZrd1Q3Nmx3REMwZS10bGtnAAAAAA2V25MWQWR4UFp5QUpSTEN4WHNrV1dULWFuURZpNWx3cFZnSVRZRzFCdXJaQWoybVl3AAAAAA0BwQcWYWRmM3N3QUFScjJ2eW1WM0tXRUh0dxZBUFJYUGMyVVRWYVNZTHhxb19GM0dBAAAAAA19TrYWX3F2NkNhVkdTVTJQRDNnSk1JcThoQRZoRTYxYjhrclNSLUNzeE9veGxaSXlnAAAAAA2CwZ0WLXAzSl9POGVSNi04alJnX2V0WlJUZxZPRzZpWTRpbFR1YVhJZl9nUU1rTk9nAAAAAAyM6fcWbkc5YUdvVllTa2FQRDdFWld3SmlGURZfSkNXU2lyeVRfV0lIN1VJR0ZDb0NnAAAAAA2tnXUWREt1cTRCNTZUU2VmeTEzS0lCSThSQRZOUE02MS04Q1NKYUFvVTJCVVI4dU1RAAAAAAzyQ0wWWUxwNDFmaE5SSUNZX0FfVzhXMGk5URZNZ3o5aE5CLVJFYVNLVmxPbk5Say1BAAAAAAy9e3wWLU5LZDI1ZGNSNUNhX09GTzdkUjhzURZIeXVmZ1d5TVJkYTJuOTNNRVNwTS1RAAAAAAyejRYWNDRQUXhac3hUc2FDSUZrem1raHBPQRYwUGRIX21RNlIweXg3MmdMMjR5aHNBAAAAAA1cC5MWaFRkQlVTSnVRRHlhWVhOdVlBMmZTQRZVZWsxQVVMQVNfcUtIZlhiMWZhaGl3AAAAAA0k6KYWR2VzeExWYXdSQkNvaVNWM3pLeHlQURZSX3NjdTZrd1Q3Nmx3REMwZS10bGtnAAAAAA2V25QWQWR4UFp5QUpSTEN4WHNrV1dULWFuURZ4QmVvZ3VzTlNhZS13Rk1OZE9wcUlRAAAAAAzh-Y4WclM5TF83OVlSeTI3TUhfR0UxNVplZxZYNVFvYU9nNFNLV2ZqcjZuMFVoNGlRAAAAAAziT6wWcVVmWm16NV9UbG0ybmQ3bnJJd2h1dxYyNWkyUzBvdFFfaVpoM1ZJUVV0dXBnAAAAAA0OLFcWQWhKNktlMTFUMmlkTnJhaDlNWVFkURZwX3RnU2dPY1NlLXlvaUNQTXNSTWxnAAAAAAzbgGoWaTNmSHIxMFZRaTZyV2JzRVplWnBwZxZ4NGY4cmFDY1E4LVZOdFVPTjZxQTdnAAAAAA0xBY0WNXN5VHpmTjZUU2VnYnhYSHdYMlkyQRZJTTR6dF9uTVRQdUM0SE85TXg0SVNnAAAAAA0fg7cWYWVNU3hEQzBSNVc0SHJtN1FmYW5jZxZlV0d2WGk1Q1JYbVNKV0NCVHVMUkp3AAAAAAybuUkWMEZKR1kxNkhUY0tEaU9laVBKS0kwdxYyZ1NHdmJTcVEzLWh3NVAzbUgyV3RBAAAAAA1jojgWZnF2ZkFRMldRZHl0OTlqZUNLbWVxQRZrVzdSbDdla1RGdTlVc0NLSGhEN19nAAAAAA04L0cWX1NYdVctdFZUWlNUZnNsakhiOXI4dxZCa0RSQWVqT1RxU1RsNzN2YnFxR3pBAAAAAA0wN10WckFXaEJ2a19UTWFDUjVjV1lDOFlqZxZQdllUTFIxNVRsU3BqcWFiblBHLU5BAAAAAA0cwncWbHg0Mm9kRTRRYzJtdmtpX0E1ejlMdxYzTW9PTG4tNlJKbUlUZnEtcEJNYjdnAAAAAA1n5cIWX09ESEUtelZRSmVTQnRuVmFuQ3RFdxZEa3dRVFhBc1R4VzNTazB6MG45dTJBAAAAAAwzIsQWdk5WZ0RJLUlSM3FvOG5UckktX011URZFUklYTFNYTVNaT3gzaTZhWHd3SFVRAAAAAAzRazQWOWgwTnZZejVRTUc2ZDNDNTNfUTJQURZXQW50X19laFNYdWVFVnhWZGVlbHNnAAAAAAz2e1MWUVNabUxhX1JUTDJpVUxrWE1tWm9CURZwTWtyU25iZlFvLVE1T2pDeDJGU2tnAAAAAA2lyx4WVkVQNjQxX3NRVEdCOFJUSVNmYklzdxY2dVNrYm5XclN6T0luTUxSZjBZV213AAAAAA07-VcWTVNWUVJKdnNRQzZHaEZaamhhZ3o3QRZ4NGY4cmFDY1E4LVZOdFVPTjZxQTdnAAAAAA0xBY4WNXN5VHpmTjZUU2VnYnhYSHdYMlkyQRZwYjB6MzQyblJyMlhpZnZmM01tMDNnAAAAAA0GbAgWbkdJRGpDMlJROXFTTEx4NmloNU1YdxZFUklYTFNYTVNaT3gzaTZhWHd3SFVRAAAAAAzRazYWOWgwTnZZejVRTUc2ZDNDNTNfUTJQURZ4QmVvZ3VzTlNhZS13Rk1OZE9wcUlRAAAAAAzh-Y8WclM5TF83OVlSeTI3TUhfR0UxNVplZxZvT3hmQ3lOY1FYS3FYdl9td0h6RWNBAAAAAA0KCJ0WXzJXdjhHS2VRcHl6S1VQNUJkZkQ3URYyNWkyUzBvdFFfaVpoM1ZJUVV0dXBnAAAAAA0OLFgWQWhKNktlMTFUMmlkTnJhaDlNWVFkURZwYjB6MzQyblJyMlhpZnZmM01tMDNnAAAAAA0GbAkWbkdJRGpDMlJROXFTTEx4NmloNU1YdxZNZ3o5aE5CLVJFYVNLVmxPbk5Say1BAAAAAAy9e30WLU5LZDI1ZGNSNUNhX09GTzdkUjhzURZ5SFZzajN3WFFWcWloVWZJYk9SemVnAAAAAAz153wWb0p1QThsSm9Sd3lHNGc5OVFpTTMydxZVQ05lXzFnTVFBaU1nSS0xalhsNF93AAAAAAzeJrYWbXdMWkxsQmFUZHFsSkxoRGZHb2lFQRZUYnBJYnRUM1FFaWFub00ySjVNb0ZRAAAAAAz1IGAWOURpbnIyOTZUZ0NaNXNTSUw1ZTNWdxZoRTYxYjhrclNSLUNzeE9veGxaSXlnAAAAAA2CwZ8WLXAzSl9POGVSNi04alJnX2V0WlJUZxZmbkxmYTdPNlRPaVJNdjQtaU5lcl9RAAAAAA0pnKwWdV85bzBaOE5RTE92bG1SRW5HNkhkURZXOERhMnB4bFRNQ1hhX0tVS0RoWlJnAAAAAA0o5SgWOWZfdzNxU1JSQTJBSmtOQ3E5dTVsURZFOHBILWgyRFFEcWNSZkJ5Y25GM25BAAAAAA2kZp4WbTMzUVZZbnlRSW1NZEF0R1d1a2lhZxZPRzZpWTRpbFR1YVhJZl9nUU1rTk9nAAAAAAyM6fgWbkc5YUdvVllTa2FQRDdFWld3SmlGURZkbUJfTXBBRFJnZV8zeWhqZUxSajlBAAAAAAzaJ7gWU2JhTWZ6ZTdTMDJ5dVlHLVJYeGk1dxYxOXlscnNYelI1U3BGalM0SnplTUJ3AAAAAA0k9pgWek5uaU45ZVhST1dJaDk2VHUzS3V5ZxY4U0dYaS0zclN6bVVJZkpLempJem9RAAAAAAy9UJcWcnNBWFVHLV9UX0swM21lbVh3STZfZxZVZWsxQVVMQVNfcUtIZlhiMWZhaGl3AAAAAA0k6KgWR2VzeExWYXdSQkNvaVNWM3pLeHlQURZvb3hWSlZia1JmdXhydkdSMlpLNkNBAAAAAA0JvCUWckE3T1duRWxTZEdUdEFydmE3MVo0URZ4WHBEWGZTR1NWNi1nVVhTUjNvdW5nAAAAAA1NsfYWalhNTlU3VEFRbzZZeXJBeFdDYWdXQRZCU01felRVQlF2Q3Z0SktLa01pYmx3AAAAAAwFargWdkhzUzI3d29RbVNMLUpydER1Z3lHURZSaDVMQ05OclRaLS1PdEFSOGc0NVpnAAAAAAvOlP8WUnlFclZEcjlTVWFlemFoZXNNMlJQZxZ0bG9Bdzl2WlRtcWpGeGhrcmxBNVF3AAAAAA0uOfIWaWdoLTVMakpUNWVnaEwtWHRtQzdjQRZacElqZ3RTZ1ItMlYzdlJzS1RkZGF3AAAAAAzCGhAWSWZxSENINmNSeXV2T0RjRE9ONC1tdxZRR0FPN2xDUlRYS29Yam54VlhIVEZBAAAAAA0HehsWNlVrcjhrNmJUbHlvdml3aVA0TnZOdxZKMGQ5dHNLUFNRZWw2ZGZvemN3WUFnAAAAAAycXqgWQXpEbDZxV2ZRNWlqY1U4b2lKREFTZxZ5T1FDRmRiSVJyaXdfUm1SOTVTQTZ3AAAAAA0vPqUWaW91VFZJZDlTcDZMVmxhZ2s5NDBWURY4YmNWVEtDQ1RTZUxrRTlUeWh6YUN3AAAAAA059GAWaFJmYlNSYkNRQ3VxNjFmVGFzR05pQQ==",
    "page_size": 10
}

module.exports = coreOta

