const vrbo = {
    "total_count": 10,
    "sentences": [
        {
            "sentence_id": 8234924315,
            "created_date": 1695230393709,
            "natural_id": "650b29b79bfffe046b559680",
            "attributes": {
                "_language": "english",
                "review_id": "650b29b79bfffe046b559680",
                "hr_tspid": "83",
                "cb_document_word_count": 42,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385275079,
                "hr_servicescore": 0,
                "ha_tuid": "5eb4563c-1717-4567-beb1-b342efc70284",
                "_languagedetected": "english",
                "_sentence_end_pos": 43,
                "_id_batch": 61535523,
                "_id_document": 5417284446,
                "ha_hotelname": "hotel 11",
                "hr_tpid": -2,
                "hr_product_brand": "ho",
                "hr_ecofriendlyscore": "0.0",
                "hr_recommended": "true",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "22:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 5,
                "natural_id": "650b29b79bfffe046b559680",
                "cb_date_updated": 1695230394029,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "220023663",
                "_degreesentimentindex": -1,
                "_sentence_start_pos": 0,
                "cb_date_created_utc": 1695230393709,
                "hr_roomcleanlinesssc": 5,
                "cb_sentence_word_count": 7,
                "cb_content_type": "contentful",
                "hr_itin": "8f2bb04d-322b-41b6-b935-995f1fdd2991",
                "_id_sentence": 8234924315,
                "_doc_time": "2023-09-20T17:19:51.000Z",
                "hr_displaylocale": "en_us",
                "hr_hotelconditionsco": 0,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "adm_expediahotelid": "25138668",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "urs",
                "cb_sentence_quartile": 1,
                "_words": "Other than issues with the pool being green",
                "review_title": "great location!",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "H&S VRBO Model - REF": [
                    "H&S VRBO Model - REF >> Pool Unclean Water"
                ]
            },
            "classification_timestamps": {
                "H&S VRBO Model - REF": 1695236081089
            }
        },
        {
            "sentence_id": 8234948999,
            "created_date": 1695241140341,
            "natural_id": "650b53aeab6a40063a09cc3c",
            "attributes": {
                "_language": "english",
                "review_id": "650b53aeab6a40063a09cc3c",
                "hr_tspid": "83",
                "cb_document_word_count": 21,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385286532,
                "hr_servicescore": 0,
                "ha_tuid": "580b7e41-b095-43f2-b686-0f9f0958fc5b",
                "_languagedetected": "english",
                "_sentence_end_pos": 130,
                "_id_batch": 61537599,
                "_id_document": 5421273449,
                "ha_hotelname": "hotel 12",
                "hr_tpid": -2,
                "hr_product_brand": "ho",
                "hr_ecofriendlyscore": "0.0",
                "hr_recommended": "true",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "01:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 4,
                "natural_id": "650b53aeab6a40063a09cc3c",
                "cb_date_updated": 1695241140623,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "221186074",
                "_degreesentimentindex": -2.5,
                "_sentence_start_pos": 45,
                "cb_date_created_utc": 1695241140341,
                "hr_roomcleanlinesssc": 4,
                "cb_sentence_word_count": 15,
                "cb_content_type": "contentful",
                "hr_itin": "ad6550a5-53a5-4c8a-8eab-a0c2d8b93e71",
                "_id_sentence": 8234948999,
                "_doc_time": "2023-09-20T20:18:52.000Z",
                "hr_displaylocale": "en_us",
                "hr_hotelconditionsco": 0,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "adm_expediahotelid": "22223208",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "urs",
                "cb_sentence_quartile": 2,
                "_words": "pools was stayed dirty never cleaned and hot tubs full of sand not cleaned out either",
                "review_title": "pools",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "H&S VRBO Model - REF": [
                    "H&S VRBO Model - REF >> Pool Unclean Water"
                ]
            },
            "classification_timestamps": {
                "H&S VRBO Model - REF": 1695245443929
            }
        },
        {
            "sentence_id": 8234965394,
            "created_date": 1695248881786,
            "natural_id": "650b71ec944ef9793c8be246",
            "attributes": {
                "_language": "english",
                "review_id": "650b71ec944ef9793c8be246",
                "hr_tspid": "83",
                "cb_document_word_count": 272,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385294178,
                "hr_servicescore": 0,
                "ha_tuid": "8ac0de97-5d2e-4f11-83f3-b7aab85c8305",
                "_languagedetected": "english",
                "_sentence_end_pos": 1498,
                "_id_batch": 61547495,
                "_id_document": 5423172454,
                "ha_hotelname": "hotel 13",
                "hr_tpid": -2,
                "cb_emotion_intensity": 2,
                "hr_product_brand": "ho",
                "hr_ecofriendlyscore": "0.0",
                "hr_recommended": "true",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "03:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 4,
                "natural_id": "650b71ec944ef9793c8be246",
                "cb_date_updated": 1695248884781,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "315551864",
                "_degreesentimentindex": -1.75,
                "_sentence_start_pos": 851,
                "cb_date_created_utc": 1695248881786,
                "hr_roomcleanlinesssc": 3,
                "cb_sentence_word_count": 122,
                "cb_content_type": "contentful",
                "hr_itin": "4a7d7f5b-48ac-49dc-8a59-ab6c783a6362",
                "_id_sentence": 8234965394,
                "_doc_time": "2023-09-20T22:27:54.000Z",
                "hr_displaylocale": "en_us",
                "hr_hotelconditionsco": 0,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "adm_expediahotelid": "70989037",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "urs",
                "cb_sentence_quartile": 3,
                "_words": "- Shampoo/conditioner/soap provided were smaller than what a hotel would provide for a place that sleeps 10 ( bring your own) - Ended up having to buy extra toilet paper/paper towels as we ran out with at most 7 people in the home at a time and no extras provided - Attempted to use grill several times and it did not heat up enough to be usable despite hooking up our own propane tank - Power was out overnight one night we were there (problematic for groceries/breastmilk) - There is a makeshift fire pit we never used, we would have loved an actual fire pit for cooking smores - Lack of AC was not an issue this time of year but would be in summer",
                "cb_sentence_ease_score": -2,
                "review_title": "fun family/dog getaway",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "H&S VRBO Model - REF": [
                    "H&S VRBO Model - REF >> Electrical - Power Outage"
                ]
            },
            "classification_timestamps": {
                "H&S VRBO Model - REF": 1695254531116
            }
        },
        {
            "sentence_id": 8234870616,
            "created_date": 1695204773820,
            "natural_id": "650ac5a152c59a38534663e4",
            "attributes": {
                "_language": "english",
                "review_id": "650ac5a152c59a38534663e4",
                "hr_tspid": "83",
                "cb_document_word_count": 120,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385249856,
                "hr_servicescore": 0,
                "ha_tuid": "020c8487-1559-4082-a0a0-74b87bef583f",
                "_languagedetected": "english",
                "_sentence_end_pos": 655,
                "_id_batch": 61528966,
                "_id_document": 5408399446,
                "ha_hotelname": "hotel 14",
                "hr_tpid": -2,
                "hr_product_brand": "ho",
                "hr_ecofriendlyscore": "0.0",
                "hr_recommended": "true",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "15:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 4,
                "natural_id": "650ac5a152c59a38534663e4",
                "cb_date_updated": 1695204775346,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "213664641",
                "_degreesentimentindex": -3,
                "_sentence_start_pos": 0,
                "cb_date_created_utc": 1695204773820,
                "hr_roomcleanlinesssc": 3,
                "cb_sentence_word_count": 120,
                "cb_content_type": "contentful",
                "hr_itin": "6e6dc4d9-adcc-4339-a34f-ff1b2d1bff78",
                "_id_sentence": 8234870616,
                "_doc_time": "2023-09-20T10:12:49.000Z",
                "hr_displaylocale": "pt_pt",
                "hr_hotelconditionsco": 0,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "adm_expediahotelid": "35833792",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "urs",
                "cb_sentence_quartile": 1,
                "_words": "Its not our fist stay in this house, the place is nice however there are a few thing that could be looked after, minor details such a few electric plugs (damaged) kitchen extractor (very noisy) upstairs shower needs attention, the cleaning on the kitchen utensils (we had to wash everything before use, they were bad) lack of towels and bed linen, the garden furniture is poor as well, load of ants and other insects will appear as the windows and doors are probably 50y old and they let everything in, the only good side is the location of the propriety and the size that fit our needs, nevertheless the price is a bit on high side for all the conditions",
                "review_title": "nice place",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "H&S VRBO Model - REF": [
                    "H&S VRBO Model - REF >> Electrical - Power Outage"
                ]
            },
            "classification_timestamps": {
                "H&S VRBO Model - REF": 1695208027156
            }
        },
        {
            "sentence_id": 8234910298,
            "created_date": 1695224497491,
            "natural_id": "650b12a8ef72745eab378b63",
            "attributes": {
                "_language": "german",
                "review_id": "650b12a8ef72745eab378b63",
                "hr_tspid": "83",
                "cb_document_word_count": 24,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385268291,
                "hr_servicescore": 0,
                "ha_tuid": "0832a424-3c4a-493c-993e-7896cba47b3f",
                "_languagedetected": "german",
                "_sentence_end_pos": 130,
                "cb_bc_person": [
                    "im",
                    "haus",
                    "steil"
                ],
                "_id_batch": 61534128,
                "_id_document": 5414778447,
                "ha_hotelname": "hotel 15",
                "hr_tpid": -2,
                "hr_product_brand": "ho",
                "hr_ecofriendlyscore": "0.0",
                "hr_recommended": "true",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "20:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 5,
                "natural_id": "650b12a8ef72745eab378b63",
                "cb_date_updated": 1695224498173,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "217348266",
                "_degreesentimentindex": 0,
                "_sentence_start_pos": 60,
                "cb_bc_detected": [
                    "person"
                ],
                "cb_date_created_utc": 1695224497491,
                "hr_roomcleanlinesssc": 5,
                "cb_sentence_word_count": 12,
                "cb_content_type": "contentful",
                "hr_itin": "65cfe861-4323-42f0-9459-0fba3e8e8fb7",
                "_id_sentence": 8234910298,
                "_doc_time": "2023-09-20T15:41:26.000Z",
                "hr_displaylocale": "de_de",
                "hr_hotelconditionsco": 0,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "adm_expediahotelid": "33478858",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "urs",
                "cb_sentence_quartile": 2,
                "_words": "Die Treppe im Haus ist zwar steil, hat aber ein ordentliches Geländer.",
                "review_title": "schöner urlaub",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "H&S VRBO Model - REF": [
                    "H&S VRBO Model - REF >> Accommodation",
                    "H&S VRBO Model - REF >> Stairs"
                ]
            },
            "classification_timestamps": {
                "H&S VRBO Model - REF": 1695231543732
            }
        },
        {
            "sentence_id": 8234931917,
            "created_date": 1695233268805,
            "natural_id": "650b34f1c311bb09881666ec",
            "attributes": {
                "_language": "english",
                "review_id": "650b34f1c311bb09881666ec",
                "hr_tspid": "83",
                "cb_document_word_count": 129,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385278572,
                "hr_servicescore": 0,
                "ha_tuid": "8d9f91fa-6c7f-4e16-80c5-f92906150b13",
                "_languagedetected": "english",
                "_sentence_end_pos": 341,
                "_id_batch": 61535523,
                "_id_document": 5418617446,
                "ha_hotelname": "hotel 16",
                "hr_tpid": -2,
                "hr_product_brand": "ho",
                "hr_ecofriendlyscore": "0.0",
                "hr_recommended": "true",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "23:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 4,
                "natural_id": "650b34f1c311bb09881666ec",
                "cb_date_updated": 1695233269469,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "215808605",
                "_degreesentimentindex": -2,
                "_sentence_start_pos": 221,
                "cb_date_created_utc": 1695233268805,
                "hr_roomcleanlinesssc": 3,
                "cb_sentence_word_count": 23,
                "cb_content_type": "contentful",
                "hr_itin": "03ffbbe8-5b5a-412a-8d90-246cbcfad537",
                "_id_sentence": 8234931917,
                "_doc_time": "2023-09-20T18:07:43.000Z",
                "hr_displaylocale": "en_us",
                "hr_hotelconditionsco": 0,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "adm_expediahotelid": "33602410",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "urs",
                "cb_sentence_quartile": 2,
                "_words": "The walk up stairs (4 stories) was tough with a toddler and the stairs within the apartment were not safe for her either.",
                "review_title": "mostly what we thought we were getting, a few caveats",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "H&S VRBO Model - REF": [
                    "H&S VRBO Model - REF >> Stairs"
                ]
            },
            "classification_timestamps": {
                "H&S VRBO Model - REF": 1695236081097
            }
        },
        {
            "sentence_id": 8234837190,
            "created_date": 1695175091303,
            "natural_id": "650a51b15b225235e6f2de81",
            "attributes": {
                "_language": "english",
                "review_id": "650a51b15b225235e6f2de81",
                "hr_tspid": "83",
                "cb_document_word_count": 224,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385231062,
                "hr_servicescore": 0,
                "ha_tuid": "154ae5fa-0578-4b21-bc0d-23d35502ec75",
                "_languagedetected": "english",
                "_sentence_end_pos": 281,
                "_id_batch": 61522260,
                "_id_document": 5402891446,
                "ha_hotelname": "hotel 17",
                "hr_tpid": -2,
                "hr_product_brand": "ho",
                "hr_ecofriendlyscore": "0.0",
                "hr_recommended": "true",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "06:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 1,
                "natural_id": "650a51b15b225235e6f2de81",
                "cb_date_updated": 1695175093680,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "321482225",
                "_degreesentimentindex": -2.25,
                "_sentence_start_pos": 0,
                "cb_date_created_utc": 1695175091303,
                "hr_roomcleanlinesssc": 3,
                "cb_sentence_word_count": 57,
                "cb_content_type": "contentful",
                "hr_itin": "90cfcfd5-aa0f-461e-853e-296eea2753d8",
                "_id_sentence": 8234837190,
                "_doc_time": "2023-09-20T01:58:09.000Z",
                "hr_displaylocale": "en_us",
                "hr_hotelconditionsco": 0,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "adm_expediahotelid": "90167348",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "urs",
                "cb_sentence_quartile": 1,
                "_words": "Never in my life of renting a spot Have I ever dealt with such an unprofessional host, We have dealt with doors not closing & water leakages even with these issues we did not complain but up until the middle of our stay the power went out and the host said he would fix it the day of.",
                "review_title": "very unprofessional host",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "H&S VRBO Model - REF": [
                    "H&S VRBO Model - REF >> Electrical - Power Outage"
                ]
            },
            "classification_timestamps": {
                "H&S VRBO Model - REF": 1695179501021
            }
        },
        {
            "sentence_id": 8234853129,
            "created_date": 1695186247591,
            "natural_id": "650a7d46ac191244c813680e",
            "attributes": {
                "_language": "english",
                "review_id": "650a7d46ac191244c813680e",
                "hr_tspid": "83",
                "cb_document_word_count": 88,
                "hr_submissiontime": "2023-09-04",
                "_id_source": "not specified",
                "_id_verbatim": 15385239177,
                "hr_servicescore": 0,
                "ha_tuid": "8940c7c5-15c7-41ca-b588-2d2591393d95",
                "_languagedetected": "english",
                "_sentence_end_pos": 493,
                "_id_batch": 61524398,
                "_id_document": 5405459469,
                "ha_hotelname": "hotel 18",
                "hr_tpid": -2,
                "hr_product_brand": "ho",
                "hr_ecofriendlyscore": "0.0",
                "hr_recommended": "true",
                "_doc_date": "2023-09-04",
                "cb_interaction_type": "feedback",
                "time_of_day": "15:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 3,
                "natural_id": "650a7d46ac191244c813680e",
                "cb_date_updated": 1695186248974,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "218201627",
                "_degreesentimentindex": -1.75,
                "_sentence_start_pos": 0,
                "cb_date_created_utc": 1695186247591,
                "hr_roomcleanlinesssc": 0,
                "cb_sentence_word_count": 88,
                "cb_content_type": "contentful",
                "_id_sentence": 8234853129,
                "_doc_time": "2023-09-04T10:31:06.000Z",
                "hr_displaylocale": "en_us",
                "hr_hotelconditionsco": 0,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "approved",
                "adm_expediahotelid": "40060696",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "urs",
                "cb_sentence_quartile": 1,
                "_words": "Disliked: - broken elevator upon arrival and so many stairs, not convenient if lots of luggage - had to pick up/pay for linen and make beds and undo and bring back with keys - early 10:00 a.m. check-out, luckily elevator was fixed -mildiou on entrance door, tray full of congealed grease in oven - no trash bags - no a/c, had to leave windows open for air but above a street and the mopeds driving by all night long was unbearable LIKED: free parking elevator if working partial view of beach",
                "review_title": "actually wanted the grand palais!",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "H&S VRBO Model - REF": [
                    "H&S VRBO Model - REF >> Window"
                ]
            },
            "classification_timestamps": {
                "H&S VRBO Model - REF": 1695188933448
            }
        },
        {
            "sentence_id": 8234883856,
            "created_date": 1695211613788,
            "natural_id": "650ae05a4080ea283300368d",
            "attributes": {
                "_language": "english",
                "review_id": "650ae05a4080ea283300368d",
                "hr_tspid": "83",
                "cb_document_word_count": 35,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385255516,
                "hr_servicescore": 0,
                "ha_tuid": "46c6d5d4-80d6-471b-a6f4-5adaa1e9901c",
                "_languagedetected": "english",
                "_sentence_end_pos": 234,
                "cb_emotion": [
                    "frustration"
                ],
                "_id_batch": 61531064,
                "_id_document": 5410209467,
                "ha_hotelname": "hotel 19",
                "hr_tpid": -2,
                "cb_emotion_intensity": 5,
                "hr_product_brand": "ho",
                "hr_ecofriendlyscore": "0.0",
                "hr_recommended": "true",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "17:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 4,
                "natural_id": "650ae05a4080ea283300368d",
                "cb_date_updated": 1695211614186,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "213664394",
                "_degreesentimentindex": -2.125,
                "_sentence_start_pos": 101,
                "cb_date_created_utc": 1695211613788,
                "hr_roomcleanlinesssc": 5,
                "cb_sentence_word_count": 19,
                "cb_content_type": "contentful",
                "hr_itin": "56a2363d-166c-4015-8b7f-1801eeb1508e",
                "_id_sentence": 8234883856,
                "_doc_time": "2023-09-20T12:06:50.000Z",
                "hr_displaylocale": "en_gb",
                "hr_hotelconditionsco": 0,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "adm_expediahotelid": "33585210",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "urs",
                "cb_sentence_quartile": 2,
                "_words": "Only snags were somewhat limited electric lighting and lack of electricity sockets for , e.g. charging phones , electric shavers, etc",
                "review_title": "delightful",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "H&S VRBO Model - REF": [
                    "H&S VRBO Model - REF >> Fatality"
                ]
            },
            "classification_timestamps": {
                "H&S VRBO Model - REF": 1695217311685
            }
        },
        {
            "sentence_id": 8234915885,
            "created_date": 1695227017953,
            "natural_id": "650b1c88fecb6761f5ef1a42",
            "attributes": {
                "_language": "french",
                "review_id": "650b1c88fecb6761f5ef1a42",
                "hr_tspid": "83",
                "cb_document_word_count": 62,
                "hr_submissiontime": "2023-09-20",
                "_id_source": "not specified",
                "_id_verbatim": 15385271078,
                "hr_servicescore": 0,
                "ha_tuid": "5aa9da80-1d67-4038-82db-79d22d6fde16",
                "_languagedetected": "french",
                "_sentence_end_pos": 128,
                "cb_emotion": [
                    "fear"
                ],
                "_id_batch": 61534128,
                "_id_document": 5415781456,
                "ha_hotelname": "hotel 20",
                "hr_tpid": -2,
                "cb_emotion_intensity": 4,
                "hr_product_brand": "ho",
                "hr_ecofriendlyscore": "0.0",
                "hr_recommended": "true",
                "_doc_date": "2023-09-20",
                "cb_interaction_type": "feedback",
                "time_of_day": "21:00",
                "cb_content_subtype": "contentful",
                "hr_overallrating": 1,
                "natural_id": "650b1c88fecb6761f5ef1a42",
                "cb_date_updated": 1695227018808,
                "hr_lastmodificationt": "2023-09-20",
                "hr_roomtypeid": "316047859",
                "_degreesentimentindex": -2.25,
                "_sentence_start_pos": 64,
                "cb_date_created_utc": 1695227017953,
                "hr_roomcleanlinesssc": 0,
                "cb_sentence_word_count": 8,
                "cb_content_type": "contentful",
                "_id_sentence": 8234915885,
                "_doc_time": "2023-09-20T16:23:36.000Z",
                "hr_displaylocale": "en_us",
                "hr_hotelconditionsco": 0,
                "_verbatimtype": "hr_reviewtext",
                "hr_moderationstatus": "queued_for_lang_detect",
                "adm_expediahotelid": "74708585",
                "hr_roomcomfortscore": 0,
                "adm_datasourceid": "urs",
                "cb_sentence_quartile": 1,
                "_words": "Poussièreux et vieillot Les escaliers sont franchement dangereux",
                "review_title": "sinistre",
                "verbatim": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi maximus rutrum eros ut porta. Vestibulum at accumsan metus, sit amet dapibus mi. Sed dictum velit nec consequat tincidunt. Mauris venenatis eleifend accumsan. Aenean eget ex elementum, ornare sem vitae, semper enim. Sed eu efficitur tellus. Sed interdum arcu ac nunc."
            },
            "classifications": {
                "H&S VRBO Model - REF": [
                    "H&S VRBO Model - REF >> Stairs"
                ]
            },
            "classification_timestamps": {
                "H&S VRBO Model - REF": 1695231543732
            }
        }
    ],
    "scroll_id": "1-757271771942551560-1-ITERATE-FGluY2x1ZGVfY29udGV4dF91dWlkDnF1ZXJ5VGhlbkZldGNoPBY0dDF4OUgweVRIYTlqM21NUGtyNzFRAAAAAA2VhMYWZkZZNktLLVBRNnE2XzZTYnczU1dVdxZXQW50X19laFNYdWVFVnhWZGVlbHNnAAAAAAz3sQYWUVNabUxhX1JUTDJpVUxrWE1tWm9CURZwTWtyU25iZlFvLVE1T2pDeDJGU2tnAAAAAA2m7fUWVkVQNjQxX3NRVEdCOFJUSVNmYklzdxZBUFJYUGMyVVRWYVNZTHhxb19GM0dBAAAAAA1-Z3wWX3F2NkNhVkdTVTJQRDNnSk1JcThoQRZoRTYxYjhrclNSLUNzeE9veGxaSXlnAAAAAA2D7yYWLXAzSl9POGVSNi04alJnX2V0WlJUZxZlV0d2WGk1Q1JYbVNKV0NCVHVMUkp3AAAAAAyc0hgWMEZKR1kxNkhUY0tEaU9laVBKS0kwdxZfSkNXU2lyeVRfV0lIN1VJR0ZDb0NnAAAAAA2u1GgWREt1cTRCNTZUU2VmeTEzS0lCSThSQRY4YmNWVEtDQ1RTZUxrRTlUeWh6YUN3AAAAAA069B8WaFJmYlNSYkNRQ3VxNjFmVGFzR05pQRZmbkxmYTdPNlRPaVJNdjQtaU5lcl9RAAAAAA0quncWdV85bzBaOE5RTE92bG1SRW5HNkhkURZIeXVmZ1d5TVJkYTJuOTNNRVNwTS1RAAAAAAyfucYWNDRQUXhac3hUc2FDSUZrem1raHBPQRY2dVNrYm5XclN6T0luTUxSZjBZV213AAAAAA09HDoWTVNWUVJKdnNRQzZHaEZaamhhZ3o3QRZVZWsxQVVMQVNfcUtIZlhiMWZhaGl3AAAAAA0mDtsWR2VzeExWYXdSQkNvaVNWM3pLeHlQURZSX3NjdTZrd1Q3Nmx3REMwZS10bGtnAAAAAA2XD6EWQWR4UFp5QUpSTEN4WHNrV1dULWFuURZCU01felRVQlF2Q3Z0SktLa01pYmx3AAAAAAwGhP4WdkhzUzI3d29RbVNMLUpydER1Z3lHURZPNmM1SEpDeVRWbWwxMmFpOVFmRER3AAAAAAz3QP8WeTJwSVJjVjFRWU9YNVVCTFN1RWNPdxYyNWkyUzBvdFFfaVpoM1ZJUVV0dXBnAAAAAA0PUT8WQWhKNktlMTFUMmlkTnJhaDlNWVFkURZndmNRSjdlelF6bWR6QS1uU3NmV2FnAAAAAA1eP0UWMDQtSGVOcFZSNUd5cFA3eEJDcEZJQRZfSkNXU2lyeVRfV0lIN1VJR0ZDb0NnAAAAAA2u1GkWREt1cTRCNTZUU2VmeTEzS0lCSThSQRZJTTR6dF9uTVRQdUM0SE85TXg0SVNnAAAAAA0gnFUWYWVNU3hEQzBSNVc0SHJtN1FmYW5jZxZlV0d2WGk1Q1JYbVNKV0NCVHVMUkp3AAAAAAyc0hkWMEZKR1kxNkhUY0tEaU9laVBKS0kwdxZRR0FPN2xDUlRYS29Yam54VlhIVEZBAAAAAA0IrSYWNlVrcjhrNmJUbHlvdml3aVA0TnZOdxZEa3dRVFhBc1R4VzNTazB6MG45dTJBAAAAAAw0WTsWdk5WZ0RJLUlSM3FvOG5UckktX011URZCa0RSQWVqT1RxU1RsNzN2YnFxR3pBAAAAAA0xXY8WckFXaEJ2a19UTWFDUjVjV1lDOFlqZxZQdllUTFIxNVRsU3BqcWFiblBHLU5BAAAAAA0d038WbHg0Mm9kRTRRYzJtdmtpX0E1ejlMdxYzTW9PTG4tNlJKbUlUZnEtcEJNYjdnAAAAAA1o998WX09ESEUtelZRSmVTQnRuVmFuQ3RFdxZrVzdSbDdla1RGdTlVc0NLSGhEN19nAAAAAA05V2YWX1NYdVctdFZUWlNUZnNsakhiOXI4dxZsZ0FXbmlfUlRlaUk3aGstdW5uNU5RAAAAAAsVdUAWSy1QY0stZ05RMTJ3NmI2bWNsQnc2dxZXQW50X19laFNYdWVFVnhWZGVlbHNnAAAAAAz3sQcWUVNabUxhX1JUTDJpVUxrWE1tWm9CURZFOHBILWgyRFFEcWNSZkJ5Y25GM25BAAAAAA2lpmkWbTMzUVZZbnlRSW1NZEF0R1d1a2lhZxZSaDVMQ05OclRaLS1PdEFSOGc0NVpnAAAAAAvPrW0WUnlFclZEcjlTVWFlemFoZXNNMlJQZxZ4NGY4cmFDY1E4LVZOdFVPTjZxQTdnAAAAAA0x_TkWNXN5VHpmTjZUU2VnYnhYSHdYMlkyQRYzTW9PTG4tNlJKbUlUZnEtcEJNYjdnAAAAAA1o9-AWX09ESEUtelZRSmVTQnRuVmFuQ3RFdxZFUklYTFNYTVNaT3gzaTZhWHd3SFVRAAAAAAzSizEWOWgwTnZZejVRTUc2ZDNDNTNfUTJQURZ4QmVvZ3VzTlNhZS13Rk1OZE9wcUlRAAAAAAzjF4wWclM5TF83OVlSeTI3TUhfR0UxNVplZxZvT3hmQ3lOY1FYS3FYdl9td0h6RWNBAAAAAA0LLk8WXzJXdjhHS2VRcHl6S1VQNUJkZkQ3URYyNWkyUzBvdFFfaVpoM1ZJUVV0dXBnAAAAAA0PUUAWQWhKNktlMTFUMmlkTnJhaDlNWVFkURZJTTR6dF9uTVRQdUM0SE85TXg0SVNnAAAAAA0gnFYWYWVNU3hEQzBSNVc0SHJtN1FmYW5jZxZXbTdmWlBMRlRRT29LeWRfTFNqdmtnAAAAAAUayAkWVGU1UHMwUmRUNGlNX2d2bWR1ZTR6dxZ5SFZzajN3WFFWcWloVWZJYk9SemVnAAAAAAz3HogWb0p1QThsSm9Sd3lHNGc5OVFpTTMydxZVQ05lXzFnTVFBaU1nSS0xalhsNF93AAAAAAzfOJ4WbXdMWkxsQmFUZHFsSkxoRGZHb2lFQRZUYnBJYnRUM1FFaWFub00ySjVNb0ZRAAAAAAz2McwWOURpbnIyOTZUZ0NaNXNTSUw1ZTNWdxZoRTYxYjhrclNSLUNzeE9veGxaSXlnAAAAAA2D7ycWLXAzSl9POGVSNi04alJnX2V0WlJUZxZmbkxmYTdPNlRPaVJNdjQtaU5lcl9RAAAAAA0qungWdV85bzBaOE5RTE92bG1SRW5HNkhkURZXOERhMnB4bFRNQ1hhX0tVS0RoWlJnAAAAAA0p9NAWOWZfdzNxU1JSQTJBSmtOQ3E5dTVsURZFOHBILWgyRFFEcWNSZkJ5Y25GM25BAAAAAA2lpmoWbTMzUVZZbnlRSW1NZEF0R1d1a2lhZxZVQ05lXzFnTVFBaU1nSS0xalhsNF93AAAAAAzfOJ8WbXdMWkxsQmFUZHFsSkxoRGZHb2lFQRZkbUJfTXBBRFJnZV8zeWhqZUxSajlBAAAAAAzbN34WU2JhTWZ6ZTdTMDJ5dVlHLVJYeGk1dxYxOXlscnNYelI1U3BGalM0SnplTUJ3AAAAAA0mKQcWek5uaU45ZVhST1dJaDk2VHUzS3V5ZxY4U0dYaS0zclN6bVVJZkpLempJem9RAAAAAAy-YIMWcnNBWFVHLV9UX0swM21lbVh3STZfZxZsZ0FXbmlfUlRlaUk3aGstdW5uNU5RAAAAAAsVdUEWSy1QY0stZ05RMTJ3NmI2bWNsQnc2dxZpNWx3cFZnSVRZRzFCdXJaQWoybVl3AAAAAA0C6PEWYWRmM3N3QUFScjJ2eW1WM0tXRUh0dxY4U0dYaS0zclN6bVVJZkpLempJem9RAAAAAAy-YIQWcnNBWFVHLV9UX0swM21lbVh3STZfZxZCU01felRVQlF2Q3Z0SktLa01pYmx3AAAAAAwGhP8WdkhzUzI3d29RbVNMLUpydER1Z3lHURZwX3RnU2dPY1NlLXlvaUNQTXNSTWxnAAAAAAzccUoWaTNmSHIxMFZRaTZyV2JzRVplWnBwZxYwUGRIX21RNlIweXg3MmdMMjR5aHNBAAAAAA1dLuIWaFRkQlVTSnVRRHlhWVhOdVlBMmZTQRZ5SFZzajN3WFFWcWloVWZJYk9SemVnAAAAAAz3HokWb0p1QThsSm9Sd3lHNGc5OVFpTTMydxZPdVQtTnBTa1NkT1JHaUJwbUpDSTVnAAAAAAvETYMWTDNROWFDQWlTeXVUdFEzVDBLbTBxZxZKMGQ5dHNLUFNRZWw2ZGZvemN3WUFnAAAAAAydrGAWQXpEbDZxV2ZRNWlqY1U4b2lKREFTZxZpMnRwazRfVlIzU2tzalVNQ2ViR09nAAAAAA2YljwWVDNjYlY4SThSZGE2U1I4amNMZWMxdxZacElqZ3RTZ1ItMlYzdlJzS1RkZGF3AAAAAAzDM9EWSWZxSENINmNSeXV2T0RjRE9ONC1tdw==",
    "page_size": 10
}

module.exports = vrbo